feat(api): create api for evaluations
SPARCS-UP-Mindanao/SPARCS-Event-Platform pull request #25
Opened 2023-10-21 04:53 UTC by sharmaigne

hi ya, ang parts na di ako sure naka code comment as "NOTE" for review, thank you

2023-10-21 14:19 UTC, ArJSarmiento requested changes
Hey @sharmaigne! 

 Could you please take a moment to review the comments on the PR? Also, it would be awesome if you could include the serverless config necessary for deploying the new DynamoDB table.

When you get a chance, could you also make a test deployment on the dev environment? And just to make sure everything is working seamlessly, it might be helpful to check if it aligns well with your local environment.

Thanks for your hard work! 🌟

2023-10-21 14:19 UTC, ArJSarmiento commented on backend/usecase/evaluation_usecase.py
> +        return [EvaluationOut(**evaluations_data) for evaluations_data in evaluations_data]
These could be merged into just one list comprehension to reduce the number of iterations by half. Apply for all instances.

2023-10-21 14:19 UTC, ArJSarmiento commented on backend/usecase/evaluation_usecase.py
> +
Remove extra line break

2023-10-21 14:19 UTC, ArJSarmiento commented on backend/controller/evaluation_router.py
> +    entry_id: str = Path(..., title='Evaluation Id', alias=CommonConstants.ENTRY_ID),
We should be querying based on a combination of these three attributes:
- `eventId`
- `registrationId`
- `question`

`entryId` is not among them. Please make adjustments for this. Apply for all instances.

2023-10-21 14:19 UTC, ArJSarmiento commented on backend/repository/evaluations_repository.py
> +                    range_key_condition = Evaluation.rangeKey.startswith('')
We can set `range_key_condition = None` for this

2023-10-21 14:19 UTC, ArJSarmiento commented on backend/repository/evaluations_repository.py
> +        # NOTE: should i be using hk here or rk
Both is good

2023-10-21 14:19 UTC, ArJSarmiento commented on backend/usecase/evaluation_usecase.py
> +        evaluation = evaluation[0] # since query_evaluations returns a list
Let's add this after checking for not OK status. Otherwise, evaluation might be None which can cause an Exception.

2023-10-27 10:20 UTC, sharmaigne commented
Hi kuya, tapos na po edit hahaha, sorry kadugay.

2023-10-28 07:08 UTC, ArJSarmiento approved these changes

2023-10-28 07:08 UTC, merged